### ISSUE TITLE
Fix: Mengganti Header pada Http Client

### ISSUE THREAD

**Issue by wisnupramoedya** [wisnupramoedya/sorgum-angular#7]
Deskripsi:
Param API sudah menambahkan header token pada request client.

Deadline: Jumat, 28 Oktober 2022 jam 09.00 WIB

**Comment by s-triar** [comment]
ini bukannya udah ya. tinggal set di interceptor?

**Comment by wisnupramoedya** [comment]
Iya mas, maksudnya set bearer token di interceptor mas
